// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWvwYwVix3pgcjHnR0yK_ZKjoVKCKSsGU',
    appId: '1:706063281960:web:d0c76f6c83e1eed45aea1d',
    messagingSenderId: '706063281960',
    projectId: 'sia-app-99c1c',
    authDomain: 'sia-app-99c1c.firebaseapp.com',
    storageBucket: 'sia-app-99c1c.appspot.com',
    measurementId: 'G-YD4H3XHTSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdhEhLVllwPPqVIpS2dF5q40T201TjpAI',
    appId: '1:706063281960:android:72bce12fbe0118975aea1d',
    messagingSenderId: '706063281960',
    projectId: 'sia-app-99c1c',
    storageBucket: 'sia-app-99c1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF4zrIvcVnhmZi-il1jrAbXlL30oCV1jo',
    appId: '1:706063281960:ios:727e7f0a919f11a85aea1d',
    messagingSenderId: '706063281960',
    projectId: 'sia-app-99c1c',
    storageBucket: 'sia-app-99c1c.appspot.com',
    iosClientId: '706063281960-dpkus96d00vt9irgi0k1ii0v1lfe538l.apps.googleusercontent.com',
    iosBundleId: 'com.example.siaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF4zrIvcVnhmZi-il1jrAbXlL30oCV1jo',
    appId: '1:706063281960:ios:ed5ad3144debd9b45aea1d',
    messagingSenderId: '706063281960',
    projectId: 'sia-app-99c1c',
    storageBucket: 'sia-app-99c1c.appspot.com',
    iosClientId: '706063281960-9f8imhostjuombv525keeigehbmfob9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.siaApp.RunnerTests',
  );
}
